### ISSUE TITLE
Build failure with clang: flexible array captured in lambda expression

### ISSUE THREAD

**Issue by visq** [t-crest/poseidon#1]
`poseidon` fails to build using `clang` (3.3):

```
t-crest/poseidon/src/xmlOutput.cpp:204:21: error: variable 'co' with
  variably modified type cannot be captured in a lambda expression
                print_coord(c.to, co, max(n.rows(),n.cols()));
```

The reason is that `co` is defined as a flexible-size array that is also used in a lambda expression. I honestly do not know whether this is a limitation of `clang`, or whether the C++11 standard does not allow this.
Please fix the problem anyway, as `clang` is the standard compiler on some systems (including OS X) and `poseidon` is now part of the `patmos` toolchain (https://github.com/t-crest/patmos-misc/blob/master/build.sh).

Quick Fix:

```
diff --git a/src/xmlOutput.cpp b/src/xmlOutput.cpp
index a358c17..d57a13c 100644
--- a/src/xmlOutput.cpp
+++ b/src/xmlOutput.cpp
@@ -160,6 +160,7 @@ void xmlOutput::print_coord(const pair<int, int> r,char* co, const int max_dimen
 void xmlOutput::add_latency(const network_t& n, xml_node* tile, const vector<router_id>* destinations, router_t* r){
        xml_node latency = (*tile).append_child("latency");
        char co[2*max(n.rows(),n.cols())+3];
+       char *buf = co; // clang does not allow references to flexible arrays in lambda expressions
        // The following for loop is slow and unnecessary, can be changed to improve runtime.
        // What is needed is all the channels with the current router as the source.
        for_each(n.channels(), [&](const channel & c) {
@@ -200,8 +201,8 @@ void xmlOutput::add_latency(const network_t& n, xml_node* tile, const vector<rou
                rate = ((double)num_phits)/n.p_best();
                // Analyze the latency
                xml_node destination = latency.append_child("destination");
-               print_coord(c.to,co,max(n.rows(),n.cols()));
-               destination.append_attribute("id") = co;
+               print_coord(c.to, buf, max(n.rows(),n.cols()));
+               destination.append_attribute("id") = buf;
                destination.append_attribute("slotwaittime") = slotswaittime;
                destination.append_attribute("channellatency") = channellatency;
                destination.append_attribute("rate") = rate;
```
